-- Retirement eligibilty

SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31';


SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31';


SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1952-12-31';


SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1953-01-01' AND '1953-12-31';


SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1954-01-01' AND '1954-12-31';


SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1955-01-01' AND '1955-12-31';

-- Retirement eligibilty with hire date between 1985 and 1988

SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE (BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
	AND (HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31');

-- Retirement eligibilty count

SELECT COUNT(FIRST_NAME)
FROM EMPLOYEES
WHERE (BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
	AND (HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31');

-- Create a Table for Retirement eligibilty

SELECT EMP_NO,
	FIRST_NAME,
	LAST_NAME INTO RETIREMENT_INFO
FROM EMPLOYEES
WHERE (BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
	AND (HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31');

-- Delete a table

DROP TABLE RETIREMENT_INFO;

-- Check the table

SELECT *
FROM RETIREMENT_INFO;

-- Joining departments and dept_manager tables

SELECT D.DEPT_NAME,
	DM.EMP_NO,
	DM.FROM_DATE,
	DM.TO_DATE
FROM DEPARTMENTS AS D
INNER JOIN DEPT_MANAGER AS DM ON D.DEPT_NO = DM.DEPT_NO;

-- Joining retirement_info and dept_emp tables

SELECT RI.EMP_NO,
	RI.FIRST_NAME,
	RI.LAST_NAME,
	DE.TO_DATE
FROM RETIREMENT_INFO AS RI
LEFT JOIN DEPT_EMP AS DE ON RI.EMP_NO = DE.EMP_NO;


SELECT RI.EMP_NO,
	RI.FIRST_NAME,
	RI.LAST_NAME,
	DE.TO_DATE INTO CURRENT_EMP
FROM RETIREMENT_INFO AS RI
LEFT JOIN DEPT_EMP AS DE ON RI.EMP_NO = DE.EMP_NO
WHERE DE.TO_DATE = ('9999-01-01');


SELECT *
FROM CURRENT_EMP;

-- Employee count by department number

SELECT COUNT(CE.EMP_NO),
	DE.DEPT_NO INTO RETIRING_EMP
FROM CURRENT_EMP AS CE
LEFT JOIN DEPT_EMP AS DE ON CE.EMP_NO = DE.EMP_NO
GROUP BY DE.DEPT_NO
ORDER BY DE.DEPT_NO;


SELECT *
FROM SALARIES
ORDER BY TO_DATE DESC;

-- Create emp_info table

SELECT E.EMP_NO,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.GENDER,
	S.SALARY,
	DE.TO_DATE INTO EMP_INFO
FROM EMPLOYEES AS E
INNER JOIN SALARIES AS S ON (E.EMP_NO = S.EMP_NO)
INNER JOIN DEPT_EMP AS DE ON (E.EMP_NO = DE.EMP_NO)
WHERE (E.BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
	AND (E.HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31')
	AND (DE.TO_DATE = '9999-01-01');

-- List of managers per department

SELECT DM.DEPT_NO,
	D.DEPT_NAME,
	DM.EMP_NO,
	CE.LAST_NAME,
	CE.FIRST_NAME,
	DM.FROM_DATE,
	DM.TO_DATE INTO MANAGER_INFO
FROM DEPT_MANAGER AS DM
INNER JOIN DEPARTMENTS AS D ON (DM.DEPT_NO = D.DEPT_NO)
INNER JOIN CURRENT_EMP AS CE ON (DM.EMP_NO = CE.EMP_NO);

--
-- Department retirees

SELECT CE.EMP_NO,
	CE.FIRST_NAME,
	CE.LAST_NAME,
	D.DEPT_NAME INTO DEPT_INFO
FROM CURRENT_EMP AS CE
INNER JOIN DEPT_EMP AS DE ON (CE.EMP_NO = DE.EMP_NO)
INNER JOIN DEPARTMENTS AS D ON (DE.DEPT_NO = D.DEPT_NO);

--
-- List of retiring in sales

SELECT DE.DEPT_NO,
	D.DEPT_NAME,
	DE.EMP_NO,
	CE.LAST_NAME,
	CE.FIRST_NAME,
	DE.FROM_DATE,
	DE.TO_DATE INTO SALES_INFO
FROM DEPT_EMP AS DE
INNER JOIN DEPARTMENTS AS D ON (DE.DEPT_NO = D.DEPT_NO)
INNER JOIN CURRENT_EMP AS CE ON (DE.EMP_NO = CE.EMP_NO)
WHERE (D.DEPT_NAME = 'Sales')
	AND (DE.TO_DATE = '9999-01-01');

--
-- List of retiring in Sales and Development

SELECT DE.DEPT_NO,
	D.DEPT_NAME,
	DE.EMP_NO,
	CE.LAST_NAME,
	CE.FIRST_NAME,
	DE.FROM_DATE,
	DE.TO_DATE INTO SALES_DEVELOPMENT_INFO
FROM DEPT_EMP AS DE
INNER JOIN DEPARTMENTS AS D ON (DE.DEPT_NO = D.DEPT_NO)
INNER JOIN CURRENT_EMP AS CE ON (DE.EMP_NO = CE.EMP_NO)
WHERE (DE.TO_DATE = '9999-01-01')
	AND D.DEPT_NAME IN ('Sales','Development');


DROP TABLE SALES_DEVELOPMENT_INFO CASCADE;


SELECT *
FROM SALES_DEVELOPMENT_INFO;